include ../make_options
LDFLAGS += -ltd_base -lpthread -ldl
NAME = td_core
FILES = td_core.c
HEADERSDEPS = $(PREFIX)/include/td_base.h

include ../make_definitions
build: $(LIBBUILD)
install: $(LIBINSTALL)
clean: $(LIBCLEAN)
uninstall: $(LIBUNINSTALL)
