include ../../make_options
LDFLAGS += -ltd_base -ltdcore
NAME = dispatch
FILES = dispatch.c
HEADERSDEPS = $(PREFIX)/include/td_base.h $(PREFIX)/include/td_core.h

include ../../make_definitions
build: $(PRIVLIBBUILD)
install: $(PRIVLIBINSTALL)
clean: $(PRIVLIBCLEAN)
uninstall: $(PRIVLIBUNINSTALL)
